package se.yarin.cbhlib;

public enum GameHeaderFlags {
    CRITICAL_POSITION,
    CORRESPONDENCE_HEADER,
    FISCHER_RANDOM,
    EMBEDDED_AUDIO,
    EMBEDDED_PICTURE,
    EMBEDDED_VIDEO,
    GAME_QUOTATION,
    PATH_STRUCTURE,
    PIECE_PATH,
    TRAINING,
    SETUP_POSITION,
    VARIATIONS,
    COMMENTARY,
    SYMBOLS,
    GRAPHICAL_SQUARES,
    GRAPHICAL_ARROWS,
    TIME_NOTIFICATIONS,

    STREAM,
}
