package se.yarin.cbhlib;

public enum Medal {
    BEST_GAME,
    DECIDED_TOURNAMENT,
    MODEL_GAME,
    NOVELTY,
    PAWN_STRUCTURE,
    STRATEGY,
    TACTICS,
    WITH_ATTACK,
    SACRIFICE,
    DEFENSE,
    MATERIAL,
    PIECE_PLAY,
    ENDGAME,
    TACTICAL_BLUNDER,
    STRATEGICAL_BLUNDER,
    USER
}
