import ahoFlag from '../assets/flags/aho.svg';
import ddrFlag from '../assets/flags/ddr.svg';
import ge2Flag from '../assets/flags/ge2.svg';
import saaFlag from '../assets/flags/saa.svg';
import scgFlag from '../assets/flags/scg.svg';
import ursFlag from '../assets/flags/urs.svg';
import zaiFlag from '../assets/flags/zai.svg';

/**
 * A nation, as ChessBase has them: by IOC code, with its flag. A few, like the Channel Islands or
 * the Internet, have no flag.
 */
export interface NationInfo {
  ioc: string;
  name: string;
  /** The flag-icons code of its flag. */
  flag?: string;
  /** An image of the flag of a nation that no longer exists, like the Soviet Union. */
  flagImage?: string;
}

/** Every nation, by name. Czechoslovakia and the Russian Empire share their flags with today's. */
export const NATIONS: NationInfo[] = [
  { ioc: 'AFG', name: 'Afghanistan', flag: 'af' },
  { ioc: 'ALB', name: 'Albania', flag: 'al' },
  { ioc: 'ALG', name: 'Algeria', flag: 'dz' },
  { ioc: 'ASA', name: 'American Samoa', flag: 'as' },
  { ioc: 'AND', name: 'Andorra', flag: 'ad' },
  { ioc: 'ANG', name: 'Angola', flag: 'ao' },
  { ioc: 'AGG', name: 'Anguilla', flag: 'ai' },
  { ioc: 'ANT', name: 'Antigua Barbuda', flag: 'ag' },
  { ioc: 'ARG', name: 'Argentina', flag: 'ar' },
  { ioc: 'ARM', name: 'Armenia', flag: 'am' },
  { ioc: 'ARU', name: 'Aruba', flag: 'aw' },
  { ioc: 'AUS', name: 'Australia', flag: 'au' },
  { ioc: 'AUT', name: 'Austria', flag: 'at' },
  { ioc: 'AZE', name: 'Azerbaijan', flag: 'az' },
  { ioc: 'BAH', name: 'Bahamas', flag: 'bs' },
  { ioc: 'BRN', name: 'Bahrain', flag: 'bh' },
  { ioc: 'BAN', name: 'Bangladesh', flag: 'bd' },
  { ioc: 'BAR', name: 'Barbados', flag: 'bb' },
  { ioc: 'BAS', name: 'Basque', flag: 'es-pv' },
  { ioc: 'BLR', name: 'Belarus', flag: 'by' },
  { ioc: 'BEL', name: 'Belgium', flag: 'be' },
  { ioc: 'BIZ', name: 'Belize', flag: 'bz' },
  { ioc: 'BEN', name: 'Benin', flag: 'bj' },
  { ioc: 'BER', name: 'Bermuda', flag: 'bm' },
  { ioc: 'BHU', name: 'Bhutan', flag: 'bt' },
  { ioc: 'BOL', name: 'Bolivia', flag: 'bo' },
  { ioc: 'BIH', name: 'Bosnia Herzegovina', flag: 'ba' },
  { ioc: 'BOT', name: 'Botswana', flag: 'bw' },
  { ioc: 'BRA', name: 'Brazil', flag: 'br' },
  { ioc: 'IVB', name: 'British Virgin Islands', flag: 'vg' },
  { ioc: 'BRU', name: 'Brunei', flag: 'bn' },
  { ioc: 'BUL', name: 'Bulgaria', flag: 'bg' },
  { ioc: 'BUR', name: 'Burkina Faso', flag: 'bf' },
  { ioc: 'BDI', name: 'Burundi', flag: 'bi' },
  { ioc: 'CAM', name: 'Cambodia', flag: 'kh' },
  { ioc: 'CMR', name: 'Cameroon', flag: 'cm' },
  { ioc: 'CAN', name: 'Canada', flag: 'ca' },
  { ioc: 'CPV', name: 'Cape Verde', flag: 'cv' },
  { ioc: 'CAT', name: 'Catalonia', flag: 'es-ct' },
  { ioc: 'CAY', name: 'Cayman Islands', flag: 'ky' },
  { ioc: 'CAF', name: 'Central African Republic', flag: 'cf' },
  { ioc: 'CHA', name: 'Chad', flag: 'td' },
  { ioc: 'GCI', name: 'Channel Islands' },
  { ioc: 'CHI', name: 'Chile', flag: 'cl' },
  { ioc: 'CHN', name: 'China', flag: 'cn' },
  { ioc: 'CIA', name: 'Christmas Island', flag: 'cx' },
  { ioc: 'COA', name: 'Cocos Islands', flag: 'cc' },
  { ioc: 'COL', name: 'Colombia', flag: 'co' },
  { ioc: 'COM', name: 'Comoros', flag: 'km' },
  { ioc: 'CGO', name: 'Congo', flag: 'cg' },
  { ioc: 'COK', name: 'Cook Islands', flag: 'ck' },
  { ioc: 'CRC', name: 'Costa Rica', flag: 'cr' },
  { ioc: 'CRO', name: 'Croatia', flag: 'hr' },
  { ioc: 'CUB', name: 'Cuba', flag: 'cu' },
  { ioc: 'CYP', name: 'Cyprus', flag: 'cy' },
  { ioc: 'CZE', name: 'Czech Republic', flag: 'cz' },
  { ioc: 'TCH', name: 'Czechoslovakia', flag: 'cz' },
  { ioc: 'DEN', name: 'Denmark', flag: 'dk' },
  { ioc: 'DJI', name: 'Djibouti', flag: 'dj' },
  { ioc: 'DOM', name: 'Dominican Republic', flag: 'do' },
  { ioc: 'OTM', name: 'East-Timor', flag: 'tl' },
  { ioc: 'ECU', name: 'Ecuador', flag: 'ec' },
  { ioc: 'EGY', name: 'Egypt', flag: 'eg' },
  { ioc: 'ESA', name: 'El Salvador', flag: 'sv' },
  { ioc: 'ENG', name: 'England', flag: 'gb-eng' },
  { ioc: 'GEQ', name: 'Equatorial Guinea', flag: 'gq' },
  { ioc: 'ERI', name: 'Eritrea', flag: 'er' },
  { ioc: 'EST', name: 'Estonia', flag: 'ee' },
  { ioc: 'ETH', name: 'Ethiopia', flag: 'et' },
  { ioc: 'FGB', name: 'Falkland Islands', flag: 'fk' },
  { ioc: 'FRO', name: 'Faroe Islands', flag: 'fo' },
  { ioc: 'FIJ', name: 'Fiji', flag: 'fj' },
  { ioc: 'FIN', name: 'Finland', flag: 'fi' },
  { ioc: 'FRA', name: 'France', flag: 'fr' },
  { ioc: 'FRG', name: 'French Guyana', flag: 'gf' },
  { ioc: 'FRP', name: 'French Polynesia', flag: 'pf' },
  { ioc: 'GAB', name: 'Gabon', flag: 'ga' },
  { ioc: 'GAM', name: 'Gambia', flag: 'gm' },
  { ioc: 'GEO', name: 'Georgia', flag: 'ge' },
  { ioc: 'DDR', name: 'German Democratic Republic', flagImage: ddrFlag },
  { ioc: 'GE2', name: 'German Empire', flagImage: ge2Flag },
  { ioc: 'GER', name: 'Germany', flag: 'de' },
  { ioc: 'GHA', name: 'Ghana', flag: 'gh' },
  { ioc: 'GGB', name: 'Gibraltar', flag: 'gi' },
  { ioc: 'GBR', name: 'Great Britain', flag: 'gb' },
  { ioc: 'GRE', name: 'Greece', flag: 'gr' },
  { ioc: 'GRL', name: 'Greenland', flag: 'gl' },
  { ioc: 'GRN', name: 'Grenada', flag: 'gd' },
  { ioc: 'FGA', name: 'Guadeloupe', flag: 'gp' },
  { ioc: 'GUM', name: 'Guam', flag: 'gu' },
  { ioc: 'GUA', name: 'Guatemala', flag: 'gt' },
  { ioc: 'GUI', name: 'Guinea', flag: 'gn' },
  { ioc: 'GBS', name: 'Guinea-Bissau', flag: 'gw' },
  { ioc: 'GUY', name: 'Guyana', flag: 'gy' },
  { ioc: 'HAI', name: 'Haiti', flag: 'ht' },
  { ioc: 'HON', name: 'Honduras', flag: 'hn' },
  { ioc: 'HKG', name: 'Hong Kong', flag: 'hk' },
  { ioc: 'HUN', name: 'Hungary', flag: 'hu' },
  { ioc: 'ISL', name: 'Iceland', flag: 'is' },
  { ioc: 'IND', name: 'India', flag: 'in' },
  { ioc: 'INA', name: 'Indonesia', flag: 'id' },
  { ioc: 'ISS', name: 'International Space Station' },
  { ioc: 'NET', name: 'Internet' },
  { ioc: 'IRI', name: 'Iran', flag: 'ir' },
  { ioc: 'IRQ', name: 'Iraq', flag: 'iq' },
  { ioc: 'IRL', name: 'Ireland', flag: 'ie' },
  { ioc: 'IOM', name: 'Isle of Man', flag: 'im' },
  { ioc: 'ISR', name: 'Israel', flag: 'il' },
  { ioc: 'ITA', name: 'Italy', flag: 'it' },
  { ioc: 'CIV', name: 'Ivory Coast', flag: 'ci' },
  { ioc: 'JAM', name: 'Jamaica', flag: 'jm' },
  { ioc: 'JMY', name: 'Jan Mayen', flag: 'sj' },
  { ioc: 'JPN', name: 'Japan', flag: 'jp' },
  { ioc: 'JOR', name: 'Jordan', flag: 'jo' },
  { ioc: 'KAZ', name: 'Kazakhstan', flag: 'kz' },
  { ioc: 'KEN', name: 'Kenya', flag: 'ke' },
  { ioc: 'KIR', name: 'Kiribati', flag: 'ki' },
  { ioc: 'KOR', name: 'Korea', flag: 'kr' },
  { ioc: 'KOS', name: 'Kosovo', flag: 'xk' },
  { ioc: 'KUW', name: 'Kuwait', flag: 'kw' },
  { ioc: 'KGZ', name: 'Kyrgyzstan', flag: 'kg' },
  { ioc: 'LAO', name: 'Laos', flag: 'la' },
  { ioc: 'LAT', name: 'Latvia', flag: 'lv' },
  { ioc: 'LIB', name: 'Lebanon', flag: 'lb' },
  { ioc: 'LES', name: 'Lesotho', flag: 'ls' },
  { ioc: 'LBR', name: 'Liberia', flag: 'lr' },
  { ioc: 'LBA', name: 'Libya', flag: 'ly' },
  { ioc: 'LIE', name: 'Liechtenstein', flag: 'li' },
  { ioc: 'LTU', name: 'Lithuania', flag: 'lt' },
  { ioc: 'LUX', name: 'Luxembourg', flag: 'lu' },
  { ioc: 'MAC', name: 'Macau', flag: 'mo' },
  { ioc: 'MKD', name: 'Macedonia', flag: 'mk' },
  { ioc: 'MAD', name: 'Madagascar', flag: 'mg' },
  { ioc: 'MAW', name: 'Malawi', flag: 'mw' },
  { ioc: 'MAS', name: 'Malaysia', flag: 'my' },
  { ioc: 'MDV', name: 'Maldives', flag: 'mv' },
  { ioc: 'MLI', name: 'Mali', flag: 'ml' },
  { ioc: 'MLT', name: 'Malta', flag: 'mt' },
  { ioc: 'MHL', name: 'Marshall Islands', flag: 'mh' },
  { ioc: 'MFR', name: 'Martinique', flag: 'mq' },
  { ioc: 'MTN', name: 'Mauritania', flag: 'mr' },
  { ioc: 'MRI', name: 'Mauritius', flag: 'mu' },
  { ioc: 'MYF', name: 'Mayotte', flag: 'yt' },
  { ioc: 'MEX', name: 'Mexico', flag: 'mx' },
  { ioc: 'MIC', name: 'Micronesia', flag: 'fm' },
  { ioc: 'MDA', name: 'Moldova', flag: 'md' },
  { ioc: 'MON', name: 'Monaco', flag: 'mc' },
  { ioc: 'MGL', name: 'Mongolia', flag: 'mn' },
  { ioc: 'MNE', name: 'Montenegro', flag: 'me' },
  { ioc: 'MSG', name: 'Montserrat', flag: 'ms' },
  { ioc: 'MAR', name: 'Morocco', flag: 'ma' },
  { ioc: 'MOZ', name: 'Mozambique', flag: 'mz' },
  { ioc: 'MYA', name: 'Myanmar', flag: 'mm' },
  { ioc: 'NAM', name: 'Namibia', flag: 'na' },
  { ioc: 'NRU', name: 'Nauru', flag: 'nr' },
  { ioc: 'NEP', name: 'Nepal', flag: 'np' },
  { ioc: 'NED', name: 'Netherlands', flag: 'nl' },
  { ioc: 'AHO', name: 'Netherlands Antilles', flagImage: ahoFlag },
  { ioc: 'NCF', name: 'New Caledonia', flag: 'nc' },
  { ioc: 'NZL', name: 'New Zealand', flag: 'nz' },
  { ioc: 'NCA', name: 'Nicaragua', flag: 'ni' },
  { ioc: 'NIG', name: 'Niger', flag: 'ne' },
  { ioc: 'NGR', name: 'Nigeria', flag: 'ng' },
  { ioc: 'NNN', name: 'Niue', flag: 'nu' },
  { ioc: 'NNA', name: 'Norfolk Island', flag: 'nf' },
  { ioc: 'PRK', name: 'North Korea', flag: 'kp' },
  { ioc: 'NMI', name: 'North Mariana Islands', flag: 'mp' },
  { ioc: 'NIR', name: 'Northern Ireland', flag: 'gb-nir' },
  { ioc: 'NOR', name: 'Norway', flag: 'no' },
  { ioc: 'OMA', name: 'Oman', flag: 'om' },
  { ioc: 'PAK', name: 'Pakistan', flag: 'pk' },
  { ioc: 'PLW', name: 'Palau', flag: 'pw' },
  { ioc: 'PLE', name: 'Palestine', flag: 'ps' },
  { ioc: 'PAN', name: 'Panama', flag: 'pa' },
  { ioc: 'PAP', name: 'Papua', flag: 'pg' },
  { ioc: 'PNG', name: 'Papua New Guinea', flag: 'pg' },
  { ioc: 'PAR', name: 'Paraguay', flag: 'py' },
  { ioc: 'PER', name: 'Peru', flag: 'pe' },
  { ioc: 'PHI', name: 'Philippines', flag: 'ph' },
  { ioc: 'PIG', name: 'Pitcairn', flag: 'pn' },
  { ioc: 'POL', name: 'Poland', flag: 'pl' },
  { ioc: 'POR', name: 'Portugal', flag: 'pt' },
  { ioc: 'PUR', name: 'Puerto Rico', flag: 'pr' },
  { ioc: 'QAT', name: 'Qatar', flag: 'qa' },
  { ioc: 'RUF', name: 'Reunion', flag: 're' },
  { ioc: 'ROU', name: 'Romania', flag: 'ro' },
  { ioc: 'RUS', name: 'Russia', flag: 'ru' },
  { ioc: 'ZAR', name: 'Russian Empire', flag: 'ru' },
  { ioc: 'RWA', name: 'Rwanda', flag: 'rw' },
  { ioc: 'SAA', name: 'Saarland (Protektorat)', flagImage: saaFlag },
  { ioc: 'SAM', name: 'Samoa', flag: 'ws' },
  { ioc: 'SMR', name: 'San Marino', flag: 'sm' },
  { ioc: 'SVI', name: 'San Vincent', flag: 'vc' },
  { ioc: 'LCA', name: 'Santa Lucia', flag: 'lc' },
  { ioc: 'STP', name: 'Sao Tome and Principe', flag: 'st' },
  { ioc: 'KSA', name: 'Saudi Arabia', flag: 'sa' },
  { ioc: 'SCO', name: 'Scotland', flag: 'gb-sct' },
  { ioc: 'SEN', name: 'Senegal', flag: 'sn' },
  { ioc: 'SRB', name: 'Serbia', flag: 'rs' },
  { ioc: 'SCG', name: 'Serbia and Montenegro', flagImage: scgFlag },
  { ioc: 'SEY', name: 'Seychelles', flag: 'sc' },
  { ioc: 'SLE', name: 'Sierra Leone', flag: 'sl' },
  { ioc: 'SIN', name: 'Singapore', flag: 'sg' },
  { ioc: 'SKI', name: 'Skitts', flag: 'kn' },
  { ioc: 'SVK', name: 'Slovakia', flag: 'sk' },
  { ioc: 'SLO', name: 'Slovenia', flag: 'si' },
  { ioc: 'SOL', name: 'Solomon Islands', flag: 'sb' },
  { ioc: 'SOM', name: 'Somalia', flag: 'so' },
  { ioc: 'RSA', name: 'South Africa', flag: 'za' },
  { ioc: 'URS', name: 'Soviet Union', flagImage: ursFlag },
  { ioc: 'ESP', name: 'Spain', flag: 'es' },
  { ioc: 'SRI', name: 'Sri Lanka', flag: 'lk' },
  { ioc: 'HGB', name: 'St. Helena', flag: 'sh' },
  { ioc: 'PGB', name: 'St. Pierre and Miquelon', flag: 'pm' },
  { ioc: 'SUD', name: 'Sudan', flag: 'sd' },
  { ioc: 'SUR', name: 'Surinam', flag: 'sr' },
  { ioc: 'SVN', name: 'Svalbard', flag: 'sj' },
  { ioc: 'SWZ', name: 'Swaziland', flag: 'sz' },
  { ioc: 'SWE', name: 'Sweden', flag: 'se' },
  { ioc: 'SUI', name: 'Switzerland', flag: 'ch' },
  { ioc: 'SYR', name: 'Syria', flag: 'sy' },
  { ioc: 'TPE', name: 'Taiwan', flag: 'tw' },
  { ioc: 'TJK', name: 'Tajikistan', flag: 'tj' },
  { ioc: 'TAN', name: 'Tanzania', flag: 'tz' },
  { ioc: 'THA', name: 'Thailand', flag: 'th' },
  { ioc: 'TOG', name: 'Togo', flag: 'tg' },
  { ioc: 'TKI', name: 'Tokelau Islands', flag: 'tk' },
  { ioc: 'TGA', name: 'Tonga', flag: 'to' },
  { ioc: 'TTO', name: 'Trinidad and Tobago', flag: 'tt' },
  { ioc: 'TUN', name: 'Tunisia', flag: 'tn' },
  { ioc: 'TUR', name: 'Turkey', flag: 'tr' },
  { ioc: 'TKM', name: 'Turkmenistan', flag: 'tm' },
  { ioc: 'TCI', name: 'Turks- and Caicos Islands', flag: 'tc' },
  { ioc: 'TUV', name: 'Tuvalu', flag: 'tv' },
  { ioc: 'ISV', name: 'U.S. Virgin Islands', flag: 'vi' },
  { ioc: 'UGA', name: 'Uganda', flag: 'ug' },
  { ioc: 'UKR', name: 'Ukraine', flag: 'ua' },
  { ioc: 'UAE', name: 'United Arab Emirates', flag: 'ae' },
  { ioc: 'USA', name: 'United States', flag: 'us' },
  { ioc: 'URU', name: 'Uruguay', flag: 'uy' },
  { ioc: 'UZB', name: 'Uzbekistan', flag: 'uz' },
  { ioc: 'VAN', name: 'Vanuatu', flag: 'vu' },
  { ioc: 'VAT', name: 'Vatican', flag: 'va' },
  { ioc: 'VEN', name: 'Venezuela', flag: 've' },
  { ioc: 'VIE', name: 'Vietnam', flag: 'vn' },
  { ioc: 'WLS', name: 'Wales', flag: 'gb-wls' },
  { ioc: 'WFR', name: 'Wallis and Futuna', flag: 'wf' },
  { ioc: 'YEM', name: 'Yemen', flag: 'ye' },
  { ioc: 'ZAI', name: 'Zaire', flagImage: zaiFlag },
  { ioc: 'ZAM', name: 'Zambia', flag: 'zm' },
  { ioc: 'ZIM', name: 'Zimbabwe', flag: 'zw' },
];

const BY_IOC = new Map(NATIONS.map((n) => [n.ioc, n]));

export function nationInfo(ioc: string | undefined): NationInfo | undefined {
  return ioc ? BY_IOC.get(ioc.toUpperCase()) : undefined;
}
